### ISSUE TITLE
V2 Wifi capability

### ISSUE THREAD

**Issue by luca910** [fpv-wtf/margerine#2]
Havent looked in the system yet. Couldnt it be that, the antennas are listed as interfaces, which could be configured as Wifi clients. V2 has 2.4 GHz

**Comment by j005u** [comment]
Sadly the DJI link is derived from 4G rather than Wifi. To the best of my knowledge, and based on what I've been told by someone who knows more about DJI hardware, it's a no go.

I also tried compiling kernel modules for ethernet adapters (to start with) as the USB port can act as OTG, but all I got was a cryptic kernel panic.
